.TH GF1-SINE 1
.SH NAME
gf1-sine \- set GF1 Function Generator waveform to sinusoidal
.SH SYNOPSIS
.B gf1-sine
.RI [ SERIALNUMBER ]
.SH DESCRIPTION
.B gf1-sine
sets the waveform to sinusoidal. This command won't affect other parameters
such as amplitude or frequency.
.SH "EXIT STATUS"
Exits with a status of zero in case of success. Returns one should an error
occur.
.SH AUTHOR
Samuel Lourenço (samuel.fmlourenco@gmail.com).
.SH "SEE ALSO"
gf1-amp(1), gf1-amp50(1), gf1-clear(1), gf1-freq(1), gf1-list(1),
gf1-lockotp(1), gf1-reset(1), gf1-start(1), gf1-stop(1), gf1-tri(1)
