.TH GF1-INFO 1
.SH NAME
gf1-info \- show information about GF1 Function Generator
.SH SYNOPSIS
.B gf1-info
.RI [ SERIALNUMBER ]
.SH DESCRIPTION
.B gf1-info
shows information about the function generator device, namely the manufacturer
and product names, the serial number, the hardware revision and the maximum
current consumption.

Specifying a serial number is optional.
.SH "EXIT STATUS"
Exits with a status of zero in case of success. Returns one should an error
occur.
.SH AUTHOR
Samuel Lourenço (samuel.fmlourenco@gmail.com).
.SH "SEE ALSO"
gf1-amp(1), gf1-amp50(1), gf1-clear(1), gf1-freq(1), gf1-list(1),
gf1-lockotp(1), gf1-reset(1), gf1-sine(1), gf1-start(1), gf1-stop(1),
gf1-tri(1)
